[project]
name = "priv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "arxiv>=2.2.0",
    "crewai>=0.121.0",
    "crewai-tools>=0.45.0",
    "pydantic>=2.11.5",
    "pydantic-settings>=2.9.1",
]
